### ISSUE TITLE
Draggable

### ISSUE THREAD

**Issue by ChaudhryAtif** [craftpip/angular-confirm#10]
I was looking at the jQuery plugin, and it had draggable feature.
Was that made possible through jQueryUi? And is it possible to port over that functionality without (preferably) jQueryUi?  If that is not possible, then perhaps jQueryUi dependency could be optional. So if jQueryUi is not included, then draggable feature will not work.

**Comment by craftpip** [comment]
Hello @ChaudhryAtif 
The draggable feature is done without jqueryUI.
this feature will be added to angular-confirm soon, after the jquery dependency is removed.

**Comment by ChaudhryAtif** [comment]
Sounds good. Looking forward to it!
