### ISSUE TITLE
Pure Angular 'angular-confirm'

### ISSUE THREAD

**Issue by thinkdj** [craftpip/angular-confirm#4]
It would be great to have the jQuery dependency taken off. Most would prefer the smallest footprint for their apps.

**Comment by jofftiquez** [comment]
@thinkdj but the core of this library is jquery.

**Comment by thinkdj** [comment]
@jofftiquez I got that after commenting, and exploring craftpip's other works. 
The request still stands as a good-to-have feature request 😄  as most people wouldn't want to add jQuery overhead and might be looking for an angular-only solution for their angular projects

**Comment by jofftiquez** [comment]
@thinkdj well... actually I'd want that too :-D

**Comment by thinkdj** [comment]
After searching a lot, this is by far the best looking, UX-focused, robust modal available for Angular1.x. I'm using it :)

**Comment by jofftiquez** [comment]
@thinkdj Hey, Im thinking, have you tried angular material design?
