### ISSUE TITLE
bower packages are important

### ISSUE THREAD

**Issue by totalard** [craftpip/angular-confirm#5]

**Comment by craftpip** [comment]
Yes, i'll get this done asap

**Comment by totalard** [comment]
Thanks, My Web app completely Setup in Bower, So only your plugin is out side of bower. which is confusing. Hope you will do this Asap?

Any time schedule?

**Comment by murwa** [comment]
👍

**Comment by totalard** [comment]
will this work?

**Comment by craftpip** [comment]
I'll add it now, sorry to keep you waiting.

**Comment by totalard** [comment]
Thanks

**Comment by totalard** [comment]
Css files Not Added Automatically
Added minified file in main Section


Kindly Fix Bugs,

**Comment by totalard** [comment]
Make a small edit in Main Section of Bower.json

"main": [
        "css/angular-confirm.css",
        "js/angular-confirm.js"
    ],


it works perfect

**Comment by craftpip** [comment]
Sure, will get it done

**Comment by craftpip** [comment]
Made the changes, updated the package to v1.0.1
Let me know if its fine. 👍
