### ISSUE TITLE
Digest Cycles Infinitely After $ngConfirm open and close

### ISSUE THREAD

**Issue by mwalsh728** [craftpip/angular-confirm#6]
When we open up any #ngConfirm dialog on a page, the digest loop count just runs wild until the user leaves the page.

This is the case even when you close the dialog window.  I've tried several ideas within my controller, including manually closing, setting the $ngConfirm object to a variable and then un-setting it, but the problem does not go away.

I don't think we can implement your library until this issue is fixed.

**Comment by craftpip** [comment]
Sorry about the inconvenience. 
I'm in the process of rewriting the plugin to fix this,
Hopefully will be complete in 2 days.

**Comment by craftpip** [comment]
This is now fixed in v1.1.0
