### ISSUE TITLE
"Undefined is not a function" when escapeKey property is true

### ISSUE THREAD

**Issue by mwalsh728** [craftpip/angular-confirm#7]
I get the following error in Chrome with the following:

1. These properties are set:
     **escapeKey**: true,
     **backgroundDismiss**: true

2. Press the "Escape" key when a confirm dialog window is open

The following error in the Chrome console comes up:

> Uncaught TypeError:  undefined is not a function

**Comment by craftpip** [comment]
Thanks for dropping by,
I'm already working on a rewrite of this plugin, please hang on.
This issues will be solved in the next release by tomorrow

**Comment by craftpip** [comment]
This is fixed in v1.1.0
